# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11emVmdJjPj1unxnF1HwNUhlzVEPIwGRq
"""

pip install fastapi uvicorn openai

response_format={
    "type": "json_schema",
    "json_schema": {
        "name": "sentiment_schema",
        "schema": {
            "type": "object",
            "properties": {
                "sentiment": {
                    "type": "string",
                    "enum": ["positive", "negative", "neutral"]
                },
                "rating": {
                    "type": "integer",
                    "minimum": 1,
                    "maximum": 5
                }
            },
            "required": ["sentiment", "rating"],
            "additionalProperties": False
        }
    }
}

from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from openai import OpenAI
import os

app = FastAPI()

client = OpenAI(api_key=("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"))

# Request Model
class CommentRequest(BaseModel):
    comment: str

@app.post("/comment", response_model=dict)
async def analyze_comment(request: CommentRequest):
    if not request.comment.strip():
        raise HTTPException(status_code=400, detail="Comment cannot be empty")

    try:
        response = client.responses.create(
            model="gpt-4.1-mini",
            input=f"Analyze the sentiment of this comment: {request.comment}",
            response_format={
                "type": "json_schema",
                "json_schema": {
                    "name": "sentiment_schema",
                    "schema": {
                        "type": "object",
                        "properties": {
                            "sentiment": {
                                "type": "string",
                                "enum": ["positive", "negative", "neutral"]
                            },
                            "rating": {
                                "type": "integer",
                                "minimum": 1,
                                "maximum": 5
                            }
                        },
                        "required": ["sentiment", "rating"],
                        "additionalProperties": False
                    }
                }
            }
        )

        return response.output[0].content[0].parsed

    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

!pip install fastapi uvicorn pyngrok openai python-dotenv

# Commented out IPython magic to ensure Python compatibility.
# %%writefile main.py
# from fastapi import FastAPI, HTTPException
# from pydantic import BaseModel
# from openai import OpenAI
# import os
# 
# app = FastAPI()
# 
# client = OpenAI(api_key="YOUR_NEW_API_KEY")  # put new key here temporarily
# 
# class CommentRequest(BaseModel):
#     comment: str
# 
# @app.post("/comment")
# async def analyze_comment(request: CommentRequest):
#     if not request.comment.strip():
#         raise HTTPException(status_code=400, detail="Comment cannot be empty")
# 
#     response = client.responses.create(
#         model="gpt-4.1-mini",
#         input=f"Analyze sentiment and return rating (1-5): {request.comment}",
#         response_format={
#             "type": "json_schema",
#             "json_schema": {
#                 "name": "sentiment_schema",
#                 "schema": {
#                     "type": "object",
#                     "properties": {
#                         "sentiment": {
#                             "type": "string",
#                             "enum": ["positive", "negative", "neutral"]
#                         },
#                         "rating": {
#                             "type": "integer",
#                             "minimum": 1,
#                             "maximum": 5
#                         }
#                     },
#                     "required": ["sentiment", "rating"],
#                     "additionalProperties": False
#                 }
#             }
#         }
#     )
# 
#     return response.output[0].content[0].parsed

!uvicorn main:app --host 0.0.0.0 --port 8000 &

from pyngrok import ngrok

ngrok.set_auth_token("2xZw0EWEtZB0cBt8xrb0XPbiXic_3EJzG7wVApHANT2PQWnf1")

public_url = ngrok.connect(8000)
print(public_url)

